CREATE TABLE `demo`
(
    `id`           VARCHAR(32) NOT NULL COMMENT 'PK',
    `columnname01` VARCHAR(32) DEFAULT NULL,
    `columnname02` VARCHAR(32) DEFAULT NULL,
    `columnname03` VARCHAR(32) DEFAULT NULL,
    `columnname04` VARCHAR(32) DEFAULT NULL,
    `columnname05` VARCHAR(32) DEFAULT NULL,
    `columnname06` VARCHAR(32) DEFAULT NULL,
    `columnname07` VARCHAR(32) DEFAULT NULL,
    `columnname08` VARCHAR(32) DEFAULT NULL,
    `columnname09` VARCHAR(32) DEFAULT NULL,
    `columnname10` VARCHAR(32) DEFAULT NULL,
    `columnname11` VARCHAR(32) DEFAULT NULL,
    `columnname12` VARCHAR(32) DEFAULT NULL,
    `columnname13` VARCHAR(32) DEFAULT NULL,
    `columnname14` VARCHAR(32) DEFAULT NULL,
    `columnname15` VARCHAR(32) DEFAULT NULL,
    `columnname16` VARCHAR(32) DEFAULT NULL,
    `columnname17` VARCHAR(32) DEFAULT NULL,
    `columnname18` VARCHAR(32) DEFAULT NULL,
    `columnname19` VARCHAR(32) DEFAULT NULL,
    `columnname20` VARCHAR(32) DEFAULT NULL,
    `columnname21` VARCHAR(32) DEFAULT NULL,
    `columnname22` VARCHAR(32) DEFAULT NULL,
    `columnname23` VARCHAR(32) DEFAULT NULL,
    `columnname24` VARCHAR(32) DEFAULT NULL,
    `columnname25` VARCHAR(32) DEFAULT NULL,
    `columnname26` VARCHAR(32) DEFAULT NULL,
    `columnname27` VARCHAR(32) DEFAULT NULL,
    `columnname28` VARCHAR(32) DEFAULT NULL,
    `columnname29` VARCHAR(32) DEFAULT NULL,
    `columnname30` VARCHAR(32) DEFAULT NULL,
    `columnname31` VARCHAR(32) DEFAULT NULL,
    `columnname32` VARCHAR(32) DEFAULT NULL,
    `columnname33` VARCHAR(32) DEFAULT NULL,
    `columnname34` VARCHAR(32) DEFAULT NULL,
    `columnname35` VARCHAR(32) DEFAULT NULL,
    `columnname36` VARCHAR(32) DEFAULT NULL,
    `columnname37` VARCHAR(32) DEFAULT NULL,
    `columnname38` VARCHAR(32) DEFAULT NULL,
    `columnname39` VARCHAR(32) DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;